#!/bin/bash
#
# iPhone Mockup Video Toolkit
#
# MODES:
#   1. Composite raw screen recording into phone frame → MP4
#   2. Convert browser-exported WebM to MP4
#
# Usage:
#   ./export.sh <input_video> [output_video] [background_color]
#   ./export.sh convert <input.webm> [output.mp4]
#
# Examples:
#   ./export.sh screen-recording.mp4                     # Raw recording → mockup MP4
#   ./export.sh recording.mov output.mp4 "#1a1a2e"       # Custom bg color
#   ./export.sh recording.mp4 output.mp4 transparent      # Transparent bg → MOV
#   ./export.sh convert iphone-mockup-1234.webm final.mp4 # WebM → MP4
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAME="$SCRIPT_DIR/frame.png"

# Frame dimensions (matches the canvas-drawn frame at 3x scale)
FRAME_W=1260
FRAME_H=2592
SCREEN_X=30
SCREEN_Y=30
SCREEN_W=1200
SCREEN_H=2532

# ---- Mode: Convert WebM → MP4 ----
if [ "$1" = "convert" ]; then
    INPUT="$2"
    OUTPUT="${3:-${INPUT%.*}.mp4}"

    if [ -z "$INPUT" ]; then
        echo "Convert browser-exported WebM to MP4"
        echo ""
        echo "Usage: ./export.sh convert <input.webm> [output.mp4]"
        exit 1
    fi

    if [ ! -f "$INPUT" ]; then
        echo "Error: File not found: $INPUT"
        exit 1
    fi

    echo "Converting WebM → MP4..."
    echo "  Input:  $INPUT"
    echo "  Output: $OUTPUT"
    echo ""

    ffmpeg -y \
        -i "$INPUT" \
        -c:v libx264 -crf 18 -preset medium -pix_fmt yuv420p \
        -c:a aac -b:a 192k \
        -movflags +faststart \
        "$OUTPUT"

    if [ $? -eq 0 ]; then
        SIZE=$(du -h "$OUTPUT" | cut -f1)
        echo ""
        echo "Done! $OUTPUT ($SIZE)"
        echo "Open: open \"$OUTPUT\""
    else
        echo "Error: Conversion failed."
        exit 1
    fi
    exit 0
fi

# ---- Mode: Composite raw recording into phone frame ----
INPUT="$1"
OUTPUT="${2:-${INPUT%.*}_mockup.mp4}"
BG_COLOR="${3:-#0a0a0a}"

if [ -z "$INPUT" ]; then
    echo "iPhone Mockup Video Toolkit"
    echo ""
    echo "Usage:"
    echo "  ./export.sh <recording> [output] [bg_color]   Composite into phone frame"
    echo "  ./export.sh convert <file.webm> [output.mp4]  Convert WebM to MP4"
    echo ""
    echo "Examples:"
    echo "  ./export.sh screen-recording.mp4"
    echo "  ./export.sh recording.mov final.mp4 '#1a1a2e'"
    echo "  ./export.sh convert mockup-export.webm final.mp4"
    exit 1
fi

if [ ! -f "$INPUT" ]; then
    echo "Error: Input file not found: $INPUT"
    exit 1
fi

if [ ! -f "$FRAME" ]; then
    echo "Error: Frame image not found: $FRAME"
    echo "The frame.png is generated by the cleanup script."
    exit 1
fi

echo "iPhone Mockup Exporter"
echo "  Input:      $INPUT"
echo "  Output:     $OUTPUT"
echo "  Background: $BG_COLOR"
echo "  Frame:      ${FRAME_W}x${FRAME_H}"
echo "  Screen:     ${SCREEN_W}x${SCREEN_H} at ($SCREEN_X,$SCREEN_Y)"
echo ""

if [ "$BG_COLOR" = "transparent" ]; then
    if [[ "$OUTPUT" != *.mov ]]; then
        OUTPUT="${OUTPUT%.*}.mov"
        echo "  (Switched to .mov for transparency)"
    fi

    echo "Exporting with transparent background..."
    ffmpeg -y \
        -i "$INPUT" \
        -i "$FRAME" \
        -filter_complex "
            [0:v]scale=${SCREEN_W}:${SCREEN_H}:force_original_aspect_ratio=increase,
            crop=${SCREEN_W}:${SCREEN_H},
            format=yuva420p[scaled];

            color=c=black@0:s=${FRAME_W}x${FRAME_H}:d=1,format=yuva420p[bg];

            [bg][scaled]overlay=${SCREEN_X}:${SCREEN_Y}:shortest=1[with_video];

            [1:v]format=yuva420p,scale=${FRAME_W}:${FRAME_H}[frame_scaled];

            [with_video][frame_scaled]overlay=0:0:format=auto[out]
        " \
        -map "[out]" \
        -map 0:a? \
        -c:v prores_ks -profile:v 4444 \
        -c:a aac -b:a 192k \
        -shortest \
        "$OUTPUT"
else
    echo "Exporting with $BG_COLOR background..."
    ffmpeg -y \
        -i "$INPUT" \
        -i "$FRAME" \
        -filter_complex "
            [0:v]scale=${SCREEN_W}:${SCREEN_H}:force_original_aspect_ratio=increase,
            crop=${SCREEN_W}:${SCREEN_H}[scaled];

            color=c='${BG_COLOR}':s=${FRAME_W}x${FRAME_H}:d=1[bg];

            [bg][scaled]overlay=${SCREEN_X}:${SCREEN_Y}:shortest=1[with_video];

            [1:v]scale=${FRAME_W}:${FRAME_H}[frame_scaled];

            [with_video][frame_scaled]overlay=0:0:format=auto[out]
        " \
        -map "[out]" \
        -map 0:a? \
        -c:v libx264 -crf 18 -preset medium -pix_fmt yuv420p \
        -c:a aac -b:a 192k \
        -movflags +faststart \
        -shortest \
        "$OUTPUT"
fi

if [ $? -eq 0 ]; then
    SIZE=$(du -h "$OUTPUT" | cut -f1)
    echo ""
    echo "Done! $OUTPUT ($SIZE)"
    echo "Open: open \"$OUTPUT\""
else
    echo ""
    echo "Error: FFmpeg failed. Check the input video format."
    exit 1
fi
